### ISSUE TITLE
Update.py needs a bit of mending 

### ISSUE THREAD

**Issue by ayush4921** [petermr/dictionary#14]
It should be parallel to the structure present in this repository

**Comment by petermr** [comment]
This is not clear.
Do not use "it" - it is not clear what "it" is? if it's `Update.py`, say so. And is it capitalized?
What is the issue? "needs a bit of mending" carries no precise information.
"parallel to the structure" is unclear. What structure? where?

Please revise the issue giving filenames, directory structures if necessary. And what is the reason?

**Comment by ayush4921** [comment]
Oh yes, It was before we started working on pyamidict. Now we have got a robust project structure. Earlier the files that you committed were using some files that were not yet present in this github repo. I think it shouldn't be an issue now.
